<?php
/**
 * The template for displaying the footer on the site.
 * It does not use tailwind, it's SCSS file can be found at ./assets/src/sass/components/footer.scss.
 * The "Footer Columns" generated by PHP can be configured in functions.php.
 *
 * Contains the footer of the site as well as WP's required code and the closing body and HTML tags.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage PT_Coaching
 * @since 1.0.0
 */
?>

<!--Start Footer-->
<footer class="footer">
    <div class="footer-left">

        <!--Company Logo-->
        <img class = "logo" src="<?php the_field('footer_image_wp', 'options'); ?>">
        <div class="left-inner">
            <!--Company Info-->
            <h3>Trent Stewart</h3>
            <p class="phone-number">(865) 982-7306</p>
        </div>
    </div>

    <div class="footer-right">
        <div class="right-inner">
            <!--Wordpress Generated Link Lists-->
            <?php wp_nav_menu( array( 'theme_location' => 'footer-column-1' ) ); ?>
            <?php wp_nav_menu( array( 'theme_location' => 'footer-column-2' ) ); ?>
        </div>

    </div>
    <div class="footer-bottom">
        <div class="bot-inner">
            <!--Socials, icons from: https://fontawesome.com/ -->
            <div class="footer-icons">
                <div class="icons-inner">
                    <a href="https://www.facebook.com/trentonjstewart"><i class="fa fa-facebook" aria-label="Trent Stewart Facebook"></i></a>
                    <a href="https://www.instagram.com/trentonjstewart/?hl=en"><i class="fa fa-instagram" aria-label="Trent Stewart Instagram"></i></a>
                    <a href="https://www.youtube.com/channel/UC2_Vo0eFmYaMq3SiA0PQLaQ"><i class="fa fa-youtube" aria-label="Trent Stewart Youtube"></i></a>
                    <a href="https://foothillschurch.com/" aria-label="Foothills Church Website"><img src="<?php the_field('footer_icon_wp', 'options'); ?>" alt="Foothills Church Icon"></a>
                </div>
            <!--Copyright Info-->
            <p>Helping pastors create healthy environments that grow healthy churches.</p>
            <p>© <?php echo date("Y"); ?> Trent Stewart</p>

            </div>
    </div>
</footer>
<!--End Footer-->


<!--Wordpress Requires This-->
<?php wp_footer(); ?>

</body>
</html>

